# Generated by Django 4.2.7 on 2026-02-22 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='job_descriptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])])),
                ('extracted_keywords', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='resumes/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])])),
                ('parsed_content', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_content', models.JSONField(blank=True, null=True)),
                ('ats_score', models.FloatField()),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/optimized/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobdescription')),
                ('original_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('optimized_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.optimizedresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['-created_at'], name='api_resume_created_85c7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-created_at'], name='api_resume_user_id_91ef11_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizedresume',
            index=models.Index(fields=['-created_at'], name='api_optimiz_created_05fd40_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizedresume',
            index=models.Index(fields=['user', '-created_at'], name='api_optimiz_user_id_49f976_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizedresume',
            index=models.Index(fields=['ats_score'], name='api_optimiz_ats_sco_a9a56e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['-created_at'], name='api_jobdesc_created_7e2a23_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['user', '-created_at'], name='api_jobdesc_user_id_47a5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletter',
            index=models.Index(fields=['-created_at'], name='api_coverle_created_80219c_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletter',
            index=models.Index(fields=['user', '-created_at'], name='api_coverle_user_id_28a93f_idx'),
        ),
    ]
