# Generated by Django 4.2.7 on 2026-02-22 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailored_resume_text', models.TextField()),
                ('cover_letter_text', models.TextField()),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='generated/resumes/')),
                ('cover_letter_pdf', models.FileField(blank=True, null=True, upload_to='generated/cover_letters/')),
                ('diff_json', models.JSONField(blank=True, null=True)),
                ('ai_changes', models.JSONField(blank=True, default=list)),
                ('token_usage', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='api.job')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='api.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='api_job_created_653210_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='api_job_user_id_eabe83_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['-created_at'], name='api_generat_created_053074_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['user', '-created_at'], name='api_generat_user_id_c7a523_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['ats_score'], name='api_generat_ats_sco_7ff314_idx'),
        ),
    ]
