# Generated by Django 4.2.7 on 2026-02-22 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_generateddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='original_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='resumes/original/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])],
            ),
        ),
        migrations.AddField(
            model_name='resume',
            name='latex_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='resumes/latex/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tex'])],
            ),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='is_latex_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='tailored_resume_tex',
            field=models.FileField(blank=True, null=True, upload_to='generated/latex/'),
        ),
    ]
