# Generated by Django 4.2.7 on 2026-07-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resume_latex_and_generated_tex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedresume',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='optimizedresume',
            name='original_resume',
        ),
        migrations.RemoveField(
            model_name='optimizedresume',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoverLetter',
        ),
        migrations.DeleteModel(
            name='OptimizedResume',
        ),
    ]
