# Generated by Django 4.2.7 on 2026-02-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
